DECLARE
  START_SEQUENCE number;
  END_SEQUENCE number;
  USERNAME_PREFIX VARCHAR2(30);
  USER_PASSWORD VARCHAR2(30);

BEGIN
  START_SEQUENCE := 100;
  END_SEQUENCE := 101;
  USERNAME_PREFIX := 'workshop';
  USER_PASSWORD := 'PasswOrd_123#';
  
  FOR USERNAME IN START_SEQUENCE .. END_SEQUENCE
  LOOP
    EXECUTE IMMEDIATE 'CREATE USER ' || USERNAME_PREFIX || USERNAME || ' IDENTIFIED BY ' || USER_PASSWORD;
    EXECUTE IMMEDIATE 'GRANT DWROLE TO ' || USERNAME_PREFIX || USERNAME;                                  
  END LOOP;
END;