DECLARE
  START_SEQUENCE number;
  END_SEQUENCE number;
  USERNAME_PREFIX VARCHAR2(30);

BEGIN
  START_SEQUENCE := 100;
  END_SEQUENCE := 101;
  USERNAME_PREFIX := 'workshop';
  
  FOR USERNAME IN START_SEQUENCE .. END_SEQUENCE
  LOOP
    EXECUTE IMMEDIATE 'DROP USER ' || USERNAME_PREFIX || USERNAME;
  END LOOP;
END;